# Generated by Django 4.2.7 on 2023-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('hp', models.CharField(max_length=10)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Not to disclose')])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='NaverSocialApp',
            fields=[
            ],
            options={
                'verbose_name': 'Naver Social Application',
                'verbose_name_plural': 'Naver Social Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('socialaccount.socialapp',),
        ),
    ]
