# Generated by Django 4.0.3 on 2023-10-24 01:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('CoffeeID', models.IntegerField(primary_key=True, serialize=False)),
                ('Coffeename', models.CharField(max_length=45)),
                ('info', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'coffee',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8, '8자 이상으로 적어주세요!')])),
                ('name', models.CharField(max_length=8)),
                ('CustomerAddress', models.CharField(max_length=3000)),
                ('BirthDate', models.DateTimeField(default=datetime.date)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Roastery',
            fields=[
                ('RoasteryID', models.IntegerField(primary_key=True, serialize=False)),
                ('Roastername', models.CharField(max_length=45)),
                ('RoasteryAddress', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'roastery',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('OrderDate', models.DateTimeField()),
                ('CoffeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coffee')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='coffee',
            name='RoasteryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.roastery'),
        ),
    ]
