# Generated by Django 4.0.3 on 2023-10-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('F', '여성'), ('M', '남성')], max_length=1, null=True),
        ),
    ]
