# Generated by Django 4.2.7 on 2023-11-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='coffee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='orderDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='ordered',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
