# Generated by Django 4.0.3 on 2023-10-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='RoastingPoint',
            field=models.CharField(max_length=10),
        ),
    ]
