# Generated by Django 4.2.7 on 2023-11-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscription_alter_order_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(default='', max_length=4),
        ),
    ]
