# Generated by Django 4.0.3 on 2023-10-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coffee_roastingpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='RoastingPoint',
            field=models.TextField(),
        ),
    ]
