# Generated by Django 4.2.7 on 2023-11-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscription_coffee_subscription_orderdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='alert',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
