# Generated by Django 4.2.7 on 2023-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscription_coffee_subscription_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='coffee',
            field=models.TextField(default='[]'),
        ),
    ]
