# Generated by Django 4.0.3 on 2023-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coffee_roastingpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='CoffeeName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='CoffeeType',
            field=models.TextField(),
        ),
    ]
