# Generated by Django 4.2.7 on 2023-11-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_userid_subscription_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='userName',
            new_name='user',
        ),
    ]
