# Generated by Django 4.2.7 on 2023-11-15 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_username_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caf', models.CharField(default='', max_length=1)),
                ('blend', models.CharField(default='', max_length=1)),
                ('notes', models.TextField(default='')),
                ('sour', models.CharField(default='', max_length=1)),
                ('sweet', models.CharField(default='', max_length=1)),
                ('bitter', models.CharField(default='', max_length=1)),
                ('body', models.CharField(default='', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
